default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sokolsexamples
  username: sokolsexamples
  password: sokolsexamples
  host: localhost
  port: 5432

test:
  <<: *default
  database: sokolsexamples
  username: sokolsexamples
  password: sokolsexamples

production:
  <<: *default
  database: sokolsexamples

#CREATE DATABASE sokolsexamples;
#CREATE USER sokolsexamples WITH password 'sokolsexamples';
#GRANT ALL privileges ON DATABASE sokolsexamples TO sokolsexamples;

